### ISSUE TITLE
DEF-HU-02 - Información incorrecta de una canción del Álbum (Buscando América)

### ISSUE THREAD

**Issue by javierpita17** [org-miso/mobile#39]
Al realizar la prueba en dispositivo físico (Huawei Mate 20 Lite - Andorid 10) y Emulador Pixel API 33, se presenta un error al mostrar el nombre de una de las canciones de un álbum

![Screenshot_20221115_115917_com vinyls mobile](https://user-images.githubusercontent.com/98791998/201982107-1810a92d-9650-494c-90db-6eca70251b45.jpg)

**Comment by FranzJr** [comment]
Es por información. La cree enviando lo que no era, luego vi que me falto el atributo .text y ya se coriigio.
