### ISSUE TITLE
DEF-HU-02 - Consultar detalle de un album - API 22 (Lollipop)

### ISSUE THREAD

**Issue by javierpita17** [org-miso/mobile#41]
Se realiza prueba en emulador de Android Pixel XL (API 22), y al consultar el detalle de un álbum se cierra repentinamente la APP.

![image](https://user-images.githubusercontent.com/98791998/202344393-efe11660-9173-4a2c-80f1-2f5b5f2f25d5.png)

**Comment by FranzJr** [comment]
Solucionado
