### ISSUE TITLE
DEF-HU-03 - Titulo incorrecto en Activity de Coleccionistas

### ISSUE THREAD

**Issue by javierpita17** [org-miso/mobile#42]
* Se presenta una inconsistencia en el título del Activity de coleccionistas, donde debería ser Coleccionistas en lugar de Colecciones.

![image](https://user-images.githubusercontent.com/98791998/204943712-874a7579-6011-4abf-8cb3-5066ab5c30d0.png)

**Comment by FranzJr** [comment]
Solucionado.
